import Link from 'next/link';
import geo from '../../data/geo/india-states.json' assert { type: 'json' };

/**
 * The map of India, coloured by who governs each state.
 *
 * The paths come from data/geo/india-states.json, generated by ops/geo/build-india.mjs from a district
 * boundary set whose URL and sha256 are recorded inside the file itself. Nothing here is hand-drawn and
 * nothing is hard-coded: a state with no data loaded renders in the no-data ink and still links to its
 * page, which is the honest way to show a gap on a map.
 *
 * Server-rendered SVG with no client JavaScript. Every state is a link, so the map is keyboard-navigable
 * and works in a text browser; hover changes the STROKE, never the fill, because changing a choropleth's
 * fill on hover destroys the one thing the reader is comparing.
 */

export type MapState = {
  /** Jurisdiction id, for the link. */
  id: string;
  /** The party leading the most recent assembly, and the fill it was assigned. */
  label: string | null;
  fill: string | null;
  seats: number;
  of: number;
  year: number | null;
};

const NO_DATA = '#1d1b26';

export function IndiaMap({
  states,
  nameOf,
}: {
  states: readonly MapState[];
  /** Registry name for a jurisdiction id, so this component never carries a list of state names. */
  nameOf: (id: string) => string;
}) {
  const byName = new Map<string, MapState>();
  for (const s of states) byName.set(nameOf(s.id).toLowerCase(), s);
  const paths = Object.entries(geo.states as Record<string, string>);
  return (
    <figure className="iei-india">
      <svg viewBox={geo.viewBox} role="img" aria-label="India, coloured by the party governing each state">
        {paths.map(([name, d]) => {
          const s = byName.get(name.toLowerCase());
          const fill = s?.fill ?? NO_DATA;
          const title =
            s === undefined
              ? `${name} — not loaded`
              : `${name} — ${s.label ?? 'no result'}${s.year === null ? '' : `, ${s.year}`} (${s.seats}/${s.of})`;
          return s === undefined ? (
            <path key={name} d={d} fill={fill} className="iei-india-off">
              <title>{title}</title>
            </path>
          ) : (
            <Link key={name} href={`/pl/${s.id}`}>
              <path d={d} fill={fill}>
                <title>{title}</title>
              </path>
            </Link>
          );
        })}
      </svg>
      <figcaption>
        Boundaries: {geo.source.publisher}. Fill: leading party in each state&rsquo;s most recent assembly
        election in this registry.
      </figcaption>
    </figure>
  );
}
